#################################################################
## Automation
#################################################################


- alias: Restart HASS
  trigger:
    platform: state
    entity_id: input_boolean.restart_hass
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.restart
    
    
- alias: "Media player paused/stopped"

  trigger:
    - platform: state
      entity_id: media_player.family_room
      from: 'playing'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.plex_lights_disable
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: group.family_room_lights
      data:
       brightness: 70
       
    
- alias: "Media player playing"

  trigger:
       - platform: state
         entity_id: media_player.family_room
         to: 'playing'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.plex_lights_disable
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: group.family_room_lights
      data:
       brightness: 30